### ISSUE TITLE
Get login working on devices and simulators

### ISSUE THREAD

**Issue by pkalita-lbl** [microbiomedata/nmdc-field-notes#92]
Currently, based on work in https://github.com/microbiomedata/nmdc-server/pull/1130 and https://github.com/microbiomedata/nmdc-field-notes/pull/26, the ORCID login flow _usually_ works when using the web version. However when using a device simulator I don't think I've ever seen it complete successfully. What I see is that the login flow is initiated by making a request to the `nmdc-server` `/login` route. The `nmdc-server` handler for that route correctly redirects the user to the ORCID login page with the correct query parameters in the URL. Once ORCID credentials are entered, it redirects back to the `nmdc-server` `/token` route and this is where it fails. The handler for that route throws an exception and this is shown to the user:

![image](https://github.com/microbiomedata/nmdc-field-notes/assets/102547565/4bde3770-7fad-438d-b0f2-029e0f40cfea)

Meanwhile on the backend here is the actual error:

```backend-1  | ERROR:    Exception in ASGI application
backend-1  | Traceback (most recent call last):
backend-1  |   File "/usr/local/lib/python3.9/site-packages/uvicorn/protocols/http/httptools_impl.py", line 419, in run_asgi
backend-1  |     result = await app(  # type: ignore[func-returns-value]
backend-1  |   File "/usr/local/lib/python3.9/site-packages/uvicorn/middleware/proxy_headers.py", line 78, in __call__
backend-1  |     return await self.app(scope, receive, send)
backend-1  |   File "/usr/local/lib/python3.9/site-packages/fastapi/applications.py", line 208, in __call__
backend-1  |     await super().__call__(scope, receive, send)
backend-1  |   File "/usr/local/lib/python3.9/site-packages/starlette/applications.py", line 112, in __call__
backend-1  |     await self.middleware_stack(scope, receive, send)
backend-1  |   File "/usr/local/lib/python3.9/site-packages/starlette/middleware/errors.py", line 181, in __call__
backend-1  |     raise exc
backend-1  |   File "/usr/local/lib/python3.9/site-packages/starlette/middleware/errors.py", line 159, in __call__
backend-1  |     await self.app(scope, receive, _send)
backend-1  |   File "/usr/local/lib/python3.9/site-packages/starlette/middleware/cors.py", line 84, in __call__
backend-1  |     await self.app(scope, receive, send)
backend-1  |   File "/usr/local/lib/python3.9/site-packages/starlette/middleware/sessions.py", line 77, in __call__
backend-1  |     await self.app(scope, receive, send_wrapper)
backend-1  |   File "/usr/local/lib/python3.9/site-packages/starlette/exceptions.py", line 82, in __call__
backend-1  |     raise exc
backend-1  |   File "/usr/local/lib/python3.9/site-packages/starlette/exceptions.py", line 71, in __call__
backend-1  |     await self.app(scope, receive, sender)
backend-1  |   File "/usr/local/lib/python3.9/site-packages/starlette/routing.py", line 656, in __call__
backend-1  |     await route.handle(scope, receive, send)
backend-1  |   File "/usr/local/lib/python3.9/site-packages/starlette/routing.py", line 259, in handle
backend-1  |     await self.app(scope, receive, send)
backend-1  |   File "/usr/local/lib/python3.9/site-packages/starlette/routing.py", line 61, in app
backend-1  |     response = await func(request)
backend-1  |   File "/usr/local/lib/python3.9/site-packages/fastapi/routing.py", line 226, in app
backend-1  |     raw_response = await run_endpoint_function(
backend-1  |   File "/usr/local/lib/python3.9/site-packages/fastapi/routing.py", line 159, in run_endpoint_function
backend-1  |     return await dependant.call(**values)
backend-1  |   File "/app/./nmdc_server/auth.py", line 132, in authorize
backend-1  |     token = await oauth2_client.orcid.authorize_access_token(request)
backend-1  |   File "/usr/local/lib/python3.9/site-packages/authlib/integrations/starlette_client/integration.py", line 62, in authorize_access_token
backend-1  |     params = self.retrieve_access_token_params(request)
backend-1  |   File "/usr/local/lib/python3.9/site-packages/authlib/integrations/base_client/base_app.py", line 143, in retrieve_access_token_params
backend-1  |     params = self._retrieve_oauth2_access_token_params(request, params)
backend-1  |   File "/usr/local/lib/python3.9/site-packages/authlib/integrations/base_client/base_app.py", line 126, in _retrieve_oauth2_access_token_params
backend-1  |     raise MismatchingStateError()
backend-1  | authlib.integrations.base_client.errors.MismatchingStateError: mismatching_state: CSRF Warning! State not equal in request and response.
```

So something about the way we have this all set up is triggering authlib's cross-site request forger (CSRF) protection (note: this is _not_ the same as CORS).

**Comment by ssarrafan** [comment]
Appears active. Moving to new sprint for review. Please remove from sprint if not active.

**Comment by eecavanna** [comment]
In https://github.com/microbiomedata/nmdc-field-notes/pull/53, I made it so (a) deep linking works on iOS and (b) the app follows the path specified in the original URL. I expect those things to have had some impact on this issue (i.e. getting it closer to a resolved state, although maybe not quite there yet).

**Comment by ssarrafan** [comment]
@pkalita-lbl should this issue remain active?

**Comment by pkalita-lbl** [comment]
Yes, still waiting on a review of https://github.com/microbiomedata/nmdc-server/pull/1257
